version: 1.0.{build}
nuget:
  project_feed: true
build:
  project: NetMemoryCopy.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: n3o7eL9mRrvTrFLqfz6iZY+l5rWn35uTUf2pV7vO4KYSxPHZchWR5dlcojpez8u7
