version: 2.0.{build}
image: Visual Studio 2019
skip_tags: true
configuration: Release
nuget:
  project_feed: true
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  package_version: '{version}'
before_build:
  - nuget restore NetMemoryCopy.sln
build:
  project: NetMemoryCopy.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: lyBx1Co3ZgFy3Rn0ZpGLLt2TrL16rP8/onlcl2px8oYEmH2Bim50j6+JDALDTrax
